### ISSUE TITLE
🔧  Remove additionalProperties defaulting to false

### ISSUE THREAD

**Issue by nicolasgramlich** [bluebirds-blue-jay/schema#1]
Not explicitly defaulting it to `false` makes it align with the JSONSchema spec:

Spec:
> The additionalProperties keyword is used to control the handling of extra stuff, that is, properties whose names are not listed in the properties keyword. **By default any additional properties are allowed**.

Relevant code: https://github.com/bluebirds-blue-jay/schema/blob/master/src/factories/object.ts#L11

**Comment by SylvainEstevez** [comment]
See disclaimer: https://github.com/bluebirds-blue-jay/schema#disclaimer
